In [2]:
import pandas as pd  
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

# 1. Filtering Rows
- Multiple condition filtering: we use (&,|,~): syntax-> df[(df['column']condition)(op) df(df['column']condition)]
- Single condition filtering: syntax -> df[ df['column'] condition ]

In [3]:
import pandas as pd

# Sample DataFrame
df = pd.DataFrame({
    'name': ['Ali', 'Sara', 'Zain', 'Noor'],
    'age': [23, 30, 17, 45],
    'city': ['Lahore', 'Karachi', 'Islamabad', 'Lahore']
})
df

   name  age       city
0   Ali   23     Lahore
1  Sara   30    Karachi
2  Zain   17  Islamabad
3  Noor   45     Lahore

In [8]:
df[df['age']<30] #Filter rows where age is >25

   name  age       city
0   Ali   23     Lahore
2  Zain   17  Islamabad

In [9]:
df[(df['age']>20) & (df['city']!='Karachi')]

   name  age    city
0   Ali   23  Lahore
3  Noor   45  Lahore

# 2.Creating columns
We can:
- Combine columns using math
- Create condition-based flags (like True/False)
- Use `.apply()` or NumPy for logic-based columns

In [15]:
import pandas as pd

df = pd.DataFrame({
    'employee': ['Ali', 'Sara', 'Zain'],
    'hours_worked': [40, 35, 50],
    'hourly_rate': [500, 600, 550]
})
df['is_overtime'] = np.where(df['hours_worked'] > 40, True, False)
df['salary'] = df['hours_worked'] * df['hourly_rate']
df

  employee  hours_worked  hourly_rate  is_overtime  salary
0      Ali            40          500        False   20000
1     Sara            35          600        False   21000
2     Zain            50          550         True   27500

In [22]:
#Creating new column bonus 
df['bonus'] = np.where(df['is_overtime']==True,2000,0)
df

  employee  hours_worked  hourly_rate  is_overtime  salary  weekly_tax  bonus
0      Ali            40          500        False   20000         0.1      0
1     Sara            35          600        False   21000         0.1      0
2     Zain            50          550         True   27500         0.1   2000

In [26]:
df['weekly_tax'] = df['salary']*0.10
df

,employee,hours_worked,hourly_rate,is_overtime,salary,weekly_tax,bonus,net_pay
0,Ali,40,500,False,20000,2000.0,0,19999.9
1,Sara,35,600,False,21000,2100.0,0,20999.9
2,Zain,50,550,True,27500,2750.0,2000,29499.9

In [27]:
df['net_pay'] = df['salary'] + df['bonus'] - df['weekly_tax']
df

,employee,hours_worked,hourly_rate,is_overtime,salary,weekly_tax,bonus,net_pay
0,Ali,40,500,False,20000,2000.0,0,18000.0
1,Sara,35,600,False,21000,2100.0,0,18900.0
2,Zain,50,550,True,27500,2750.0,2000,26750.0

# 3.handling_missing
### you'll learn how to:
- Detect missing values
- Drop missing da using dropna: syntax-> df.dropna(substet[column])
- Fill missing values (imputati using fillna: syntax -> df.fillna(value))
- Practice with real examples

In [35]:
df = pd.DataFrame({
    'name': ['Ali', 'Sara', 'Zain', np.nan],
    'age': [25, np.nan, 30, 22],
    'city': ['Lahore', 'Karachi', np.nan, 'Lahore']
})
df

   name   age     city
0   Ali  25.0   Lahore
1  Sara   NaN  Karachi
2  Zain  30.0      NaN
3   NaN  22.0   Lahore

In [29]:
# to count how many missing value we have in each column we use: .isnull().sum()
df.isnull().sum()

name    1
age     1
city    1
dtype: int64

In [36]:
#Drop rows where city has NaN value 
df = df.dropna(subset=['city'])

In [37]:
#use fillna to fill missing value with no_name and age with it's median value 
df = df.fillna({
    'name':'no_name',
    'age':df['age'].median()
})

In [46]:
#final check to make sure if there is not missing values:
print(df.isnull().sum())
print(df)

name    0
age     0
city    0
dtype: int64
      name   age     city
0      Ali  25.0   Lahore
1     Sara  23.5  Karachi
3  no_name  22.0   Lahore

# 4. encoding
Machine learning models don’t understand text — they need numbers.

We use **encoding** to convert categorical values into numeric values.

We’ll cover:
- Label Encoding (use .map to assign either 1 or 0 to a categorical column) use only when dealing with columns like gender
- One-Hot Encoding (use get_dummies)
- When to use each

In [35]:
df = pd.DataFrame({
    'name': ['Ali', 'Sara', 'Zain', 'Noor'],
    'gender': ['Male', 'Female', 'Male', 'Female'],
    'department': ['HR', 'Finance', 'IT', 'HR']
})
df

   name  gender department
0   Ali    Male         HR
1  Sara  Female    Finance
2  Zain    Male         IT
3  Noor  Female         HR

In [36]:
#label encoding 
df['gender'] = df['gender'].map({'Male':0,'Female':1})

In [46]:
#one-hot encoding 
df = pd.get_dummies(df,columns=['department'], dtype=int)

In [47]:
df

   name  gender  department_Finance  department_HR  department_IT
0   Ali       0                   0              1              0
1  Sara       1                   1              0              0
2  Zain       0                   0              0              1
3  Noor       1                   0              1              0

# 5. Binning Continuous Variables

Binning helps convert continuous values into categorical buckets.

Why?
- Makes patterns easier to spot
- Reduces noise
- Sometimes improves model performance
- Use Pd.cut or np.where

In [53]:
df = pd.DataFrame({
    'name': ['Ali', 'Sara', 'Zain', 'Noor', 'Hassan', 'Ayesha'],
    'age': [17, 22, 36, 42, 29, 64]
})
df

     name  age
0     Ali   17
1    Sara   22
2    Zain   36
3    Noor   42
4  Hassan   29
5  Ayesha   64

In [54]:
# using np.where 
df['age_group_where'] = np.where(df['age']<20,'Teen',
                           np.where(df['age']<40,'Adult','senior'))

In [55]:
#using pd.cut 
bins = [0,20,40,100]
labels = ['Teen','Adult','Senior']
df['age_group_cut'] = pd.cut(df['age'],right=False,bins=bins, labels=labels)

In [56]:
df

     name  age age_group_where age_group_cut
0     Ali   17            Teen          Teen
1    Sara   22           Adult         Adult
2    Zain   36           Adult         Adult
3    Noor   42          senior        Senior
4  Hassan   29           Adult         Adult
5  Ayesha   64          senior        Senior

## Feature Scaling (To Be Covered Later)

We are **not covering feature scaling right now** since it's mostly needed during the **modeling stage**, not during basic EDA or beginner-level feature engineering.

However, here's a quick overview so you know what it's about:

---

### What is Feature Scaling?

Feature scaling means **bringing numeric values (like age, salary, height)** into the **same range** so that no one feature dominates others during model training.

It’s super important when using models like:
- KNN
- SVM
- Logistic Regression
- Neural Networks

---

### Two Common Techniques

| Method            | What it does                            | Range       |
|------------------|------------------------------------------|-------------|
| 🔹 Min-Max Scaling | Scales values between 0 and 1            | 0 → 1       |
| 🔺 Z-score Scaling | Centers values around mean 0, std 1      | ~ -3 → +3   |

You’ll learn more about these when we start **machine learning models** later.

---

For now, just remember:
> **Feature scaling prepares your data for modeling — not for exploration.**

We'll cover it in detail in a later notebook when we build models.

## 7. Text Feature Engineering

Text columns often need cleaning before analysis or modeling.

We'll cover:
- Lowercasing and trimming
- String search
- Extracting parts
- Feature creation from text

In [147]:
data = pd.DataFrame({
    'name': [' Ali Khan', 'SARA', 'Zain.', 'Noor Sheikh'],
    'email': ['ali@gmail.com', 'sara@outlook.com', 'zain@yahoo.com', 'noor@gmail.com'],
    'comment': ['Great!', 'BAD', 'Average', 'Excellent!!']
})
data

          name             email      comment
0     Ali Khan     ali@gmail.com       Great!
1         SARA  sara@outlook.com          BAD
2        Zain.    zain@yahoo.com      Average
3  Noor Sheikh    noor@gmail.com  Excellent!!

In [148]:
data['name'] = data['name'].str.strip().str.lower() #Remove spaces(strip), convert text to lowercase (lower)

In [151]:
data['Is_Gmail'] = data['email'].str.contains("@gmail.com")

In [152]:
data['domain'] = data['email'].str.extract(r'@(.+)$')

In [158]:
data['comment_sentiment'] = np.where(data['comment'].str.lower().str.contains('excellent|great'),'Positive',
                                    np.where(data['comment'].str.lower().str.contains('bad'),'Negative','Neutral'))

In [160]:
data['comment'] = data['comment'].str.replace('!', '', regex=False)

In [162]:
data

,name,email,comment,Is_Gmail,domain,comment_sentiment
0,ali khan,ali@gmail.com,Great,True,gmail.com,Positive
1,sara,sara@outlook.com,BAD,False,outlook.com,Negative
2,zain.,zain@yahoo.com,Average,False,yahoo.com,Neutral
3,noor sheikh,noor@gmail.com,Excellent,True,gmail.com,Positive

## String Cleaning Cheatsheet

- Remove extra spaces → `.str.strip()`
- Lowercase → `.str.lower()`
- Replace → `.str.replace('old', 'new')`
- Check for text → `.str.contains('keyword')`
- Extract → `.str.extract('regex')`
- Split → `.str.split('@')`

## 8. Datetime Feature Engineering

Time-based data is very common in real-world datasets.

We'll cover:
- Converting to datetime
- Extracting year, month, day
- Calculating durations
- Categorizing based on time

In [163]:
import pandas as pd

df = pd.DataFrame({
    'employee': ['Ali', 'Sara', 'Zain', 'Noor', 'Ahmed'],
    'joining_date': ['2020-01-10', '2023-03-25', '2021-07-19', '2022-11-05', '2019-09-01']
})

df['joining_date'] = pd.to_datetime(df['joining_date'])  # Convert to datetime
df

  employee joining_date
0      Ali   2020-01-10
1     Sara   2023-03-25
2     Zain   2021-07-19
3     Noor   2022-11-05
4    Ahmed   2019-09-01

In [166]:
#Extract joining year,month,day, weekday 
df['Joining_year'] = df['joining_date'].dt.year
df['Joining_month'] = df['joining_date'].dt.month
df['Joining_day'] = df['joining_date'].dt.day
df['Joining_week'] = df['joining_date'].dt.day_name()

In [171]:
#how many days since a person joined 
today = pd.Timestamp.today()
df['tenure_years'] = (today - df['joining_date']).dt.days // 365

In [172]:
#add labels
bins = [0, 1, 2, float('inf')]
labels = ['New', 'Mid', 'Experienced']
df['tenure_label'] = pd.cut(df['tenure_years'], bins=bins, labels=labels)

In [173]:
df

,employee,joining_date,Joining_month,Joining_year,Joining_day,Joining_week,days_since_joined,tenure_years,tenure_label
0,Ali,2020-01-10,1,2020,10,Friday,1986,5,Experienced
1,Sara,2023-03-25,3,2023,25,Saturday,816,2,Mid
2,Zain,2021-07-19,7,2021,19,Monday,1430,3,Experienced
3,Noor,2022-11-05,11,2022,5,Saturday,956,2,Mid
4,Ahmed,2019-09-01,9,2019,1,Sunday,2117,5,Experienced

---

## Final Note

If you've made it this far — whether you're a beginner just starting your journey or someone revisiting the basics — give yourself credit. Learning Data Science isn't just about mastering tools like Pandas or Seaborn, it's about building the *mindset* to solve problems, think critically, and keep going even when things feel messy (looking at you, string columns).

This notebook is part of my own learning journey. I'm not a pro (yet), but every line of code I wrote here helped me grow — and I hope it does the same for you.

Keep practicing. Keep breaking things. Keep fixing them.

**The goal isn’t perfection — it’s progress.**

See you at the top,  
**– [Arshiyan~]** 

---