In [1]:
import pandas as pd

In [3]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [24, 27, 22, 32, 29],
    'Score': [85, 62, 90, 70, 95]
}

df = pd.DataFrame(data)
df

      Name  Age  Score
0    Alice   24     85
1      Bob   27     62
2  Charlie   22     90
3    David   32     70
4      Eve   29     95

In [4]:
#Print all rows where score is less than 90
df[df['Score']<90]

    Name  Age  Score
0  Alice   24     85
1    Bob   27     62
3  David   32     70

In [6]:
#Select only the 'Name' and 'Age' of those whose Age is 27 or more.
df.loc[df['Age']>=27,['Name','Age']]

    Name  Age
1    Bob   27
3  David   32
4    Eve   29

In [7]:
#Select where age>25 and score is <90
df[(df['Age']>25) & (df['Score']<90)]

    Name  Age  Score
1    Bob   27     62
3  David   32     70

In [10]:
df[~df['Name'].isin(['Alice','Eve'])]

      Name  Age  Score
1      Bob   27     62
2  Charlie   22     90
3    David   32     70

In [11]:
import pandas as pd

data = {
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace'],
    'Department': ['HR', 'IT', 'Finance', 'IT', 'HR', 'Finance', 'IT'],
    'Age': [25, 30, 28, 45, 26, 35, 29],
    'Salary': [50000, 60000, 55000, 80000, 52000, 65000, 70000]
}

df1 = pd.DataFrame(data)
df1

  Employee Department  Age  Salary
0    Alice         HR   25   50000
1      Bob         IT   30   60000
2  Charlie    Finance   28   55000
3    David         IT   45   80000
4      Eva         HR   26   52000
5    Frank    Finance   35   65000
6    Grace         IT   29   70000

In [14]:
df1.loc[df1['Department']=="IT",['Employee','Department']]

  Employee Department
1      Bob         IT
3    David         IT
6    Grace         IT

In [15]:
df1.loc[df1['Age']<30,['Employee','Salary']]

  Employee  Salary
0    Alice   50000
2  Charlie   55000
4      Eva   52000
6    Grace   70000

In [19]:
#Get rows where the department is either HR or Finance and salary is greater than 55,000
df1[df1['Department'].isin(['HR','Finance']) & (df1['Salary']>55000)]

  Employee Department  Age  Salary
5    Frank    Finance   35   65000

In [21]:
df1[~(df1['Department']=='Finance')]

  Employee Department  Age  Salary
0    Alice         HR   25   50000
1      Bob         IT   30   60000
3    David         IT   45   80000
4      Eva         HR   26   52000
6    Grace         IT   29   70000

In [22]:
df1[(df1['Age']>27) & (df1['Salary']>=65000)]

  Employee Department  Age  Salary
3    David         IT   45   80000
5    Frank    Finance   35   65000
6    Grace         IT   29   70000

In [25]:
import pandas as pd

data = {
    'Name': [' Alice ', 'BOB', '  Charlie', 'bob  ', 'alice'],
    'Department': ['Finance', ' finance', 'HR', 'hr ', 'FINANCE dept'],
    'Email': ['Alice@Company.com ', 'BOB@company.COM', 'charlie @company.com', ' bob@company.com ', 'alice@company.COM']
}

df2 = pd.DataFrame(data)
df2

        Name    Department                 Email
0     Alice        Finance    Alice@Company.com
1        BOB       finance       BOB@company.COM
2    Charlie            HR  charlie @company.com
3      bob             hr       bob@company.com
4      alice  FINANCE dept     alice@company.COM

In [36]:
df2['Department'] = df2['Department'].str.replace('dept','Department')
df2['Email'] = df2['Email'].str.strip('@')
df2

        Name          Department                 Email
0     Alice              Finance    Alice@Company.com
1        BOB             finance       BOB@company.COM
2    Charlie                  HR  charlie @company.com
3      bob                   hr       bob@company.com
4      alice  FINANCE Department     alice@company.COM

In [11]:
messy_data = {
    'Product': ['  Laptop  ', 'MOUSE', '  Headphones  ', '  USB-C Cable__'],
    'Price': ['$100', '  $20', '$50  ', '  $10__']
}
df_ex = pd.DataFrame(messy_data)
df_ex

           Product    Price
0         Laptop       $100
1            MOUSE      $20
2     Headphones      $50
3    USB-C Cable__    $10__

In [14]:
def strip_whitespace(df,colums): 
    for col in colums:
        df[col] = df[col].str.strip()
        return df 
cols = ['Product','Price']
print(strip_whitespace(df_ex,cols))

         Product    Price
0         Laptop     $100
1          MOUSE      $20
2     Headphones    $50
3  USB-C Cable__    $10__

In [28]:
import re
df_ex['Product'] = df_ex['Product'].str.replace(r'[^a-zA-Z\s]', '', regex=True)

In [25]:
df_ex['Price'] = df_ex['Price'].str.replace(r'[^\d]', '', regex=True)
df_ex['Price'] = pd.to_numeric(df_ex['Price'])

In [31]:
df_ex['Product'] = df_ex['Product'].str.lower()
df_ex

      Product  Price
0      laptop    100
1       mouse     20
2  headphones     50
3  usbc cable     10

In [32]:
import pandas as pd
import numpy as np  # For NaN handling

data = {
    'OrderID': ['  #1001 ', '  #1002', '#1003  ', '  #1004', ' #1005  '],
    'Customer': ['John Doe  ', ' alice SMITH', 'Bob T.  ', '  Mary-Kate', 'DAVID_LEE'],
    'Product': ['Laptop|16GB', 'Mouse (Wireless)', '  Keyboard  ', 'Monitor-24"', 'USB-C_Cable'],
    'Price': ['$999.99', '$25.50', '  $45.00', '$200.00', '  $10.99  '],
    'Delivery_Date': ['2023-01-15', 'Invalid', '2023-01-20', '2023-01-18', 'NaN']
}

df = pd.DataFrame(data)
df

    OrderID      Customer           Product       Price Delivery_Date
0    #1001     John Doe         Laptop|16GB     $999.99    2023-01-15
1     #1002   alice SMITH  Mouse (Wireless)      $25.50       Invalid
2   #1003        Bob T.          Keyboard        $45.00    2023-01-20
3     #1004     Mary-Kate       Monitor-24"     $200.00    2023-01-18
4   #1005       DAVID_LEE       USB-C_Cable    $10.99             NaN

In [34]:
df['OrderID'] = df['OrderID'].str.strip().str.replace('#','')
df['OrderID'] = pd.to_numeric(df['OrderID'])

In [36]:
df['Customer'] = (
    df['Customer'].str.replace('_','')
    .str.strip()
    .str.title()
)

In [39]:
df['Product'] = df['Product'].str.replace(r'[^a-zA-Z]','',regex=True).str.strip()

In [42]:
df['Price'] = df['Price'].str.replace('$','').astype(float)

In [46]:
import numpy as np
df['Delivery_Date'] = df['Delivery_Date'].replace(['NaN','Invalid',''],np.nan).astype('datetime64[ns]')

In [51]:
import pandas as pd
import numpy as np

data = {
    'order_id': ['  #1001', '1002 ', '  #1003 ', '1004', '1005  '],
    'customer': ['john DOE', 'Alice Wong ', '  BOB', 'Mary-Kate', 'DAVID_LEE'],
    'item': ['Burger ', '  Pizza(Large)', 'Fries ', 'Ice-Cream', 'Soda '],
    'price': ['$10.50', '  $15.0', '$3.99', '$4.50', ' $2.25'],
    'delivery_date': ['2023-01-15', '2023-01-16', 'Invalid', '2023-01-17', 'NaN']
}

df = pd.DataFrame(data)
print("Original Data:")
df

Original Data:

   order_id     customer            item    price delivery_date
0     #1001     john DOE         Burger    $10.50    2023-01-15
1     1002   Alice Wong     Pizza(Large)    $15.0    2023-01-16
2    #1003           BOB          Fries     $3.99       Invalid
3      1004    Mary-Kate       Ice-Cream    $4.50    2023-01-17
4    1005      DAVID_LEE           Soda     $2.25           NaN

In [52]:
df['order_id'] = df['order_id'].str.replace('#','').astype(int)

In [64]:
df['customer'] = (
    df['customer'].str.title()
    .str.replace(r'[^a-zA-Z0-9]',' ',regex=True)
)

In [67]:
df['item'] = (
    df['item'].str.replace(r'\([^)]*\)','',regex=True)
    .str.strip()
)

In [56]:
df['price'] = df['price'].str.replace('$','').astype(float)

In [60]:
df['delivery_date'] = df['delivery_date'].replace(['NaN','invalid',''],np.nan)

In [68]:
df

   order_id   customer       item  price delivery_date
0      1001    Johndoe     Burger  10.50    2023-01-15
1      1002  Alicewong      Pizza  15.00    2023-01-16
2      1003        Bob      Fries   3.99       Invalid
3      1004   Marykate  Ice-Cream   4.50    2023-01-17
4      1005   Davidlee       Soda   2.25           NaN

In [69]:
sales = pd.DataFrame({  
    'item': ['Coffee', 'Tea', 'Cookie', 'Muffin'],  
    'price': [3.5, 2.0, 1.5, 2.5],  
    'quantity': [50, 120, 200, 75]  
})  
sales

     item  price  quantity
0  Coffee    3.5        50
1     Tea    2.0       120
2  Cookie    1.5       200
3  Muffin    2.5        75

In [70]:
sales['revenue'] = sales['price'] * sales['quantity']

In [81]:
sales['category'] = sales['item'].apply(lambda x: 'Beverage' if x in ['Coffee','Tea'] else 'snacks' )

In [79]:
sales['discount'] = np.where(sales['quantity']>100,sales['price']*0.85,sales['price'])

In [82]:
sales

     item  price  quantity  revenue  category  discount
0  Coffee    3.5        50    175.0  Beverage     3.500
1     Tea    2.0       120    240.0  Beverage     1.700
2  Cookie    1.5       200    300.0    snacks     1.275
3  Muffin    2.5        75    187.5    snacks     2.500

In [83]:
import pandas as pd
import numpy as np

data = {
    'member_id': [101, 102, 103, 104, 105],
    'name': ['John Doe', 'Alice Smith', 'Bob Johnson', 'Eva Williams', 'Mike Brown'],
    'membership_type': ['Basic', 'Premium', 'Basic', 'Student', 'Premium'],
    'months_active': [3, 12, 7, 2, 24],
    'monthly_fee': [30, 50, 30, 20, 50]
}

df = pd.DataFrame(data)
print("Original Data:")
df

Original Data:

   member_id          name membership_type  months_active  monthly_fee
0        101      John Doe           Basic              3           30
1        102   Alice Smith         Premium             12           50
2        103   Bob Johnson           Basic              7           30
3        104  Eva Williams         Student              2           20
4        105    Mike Brown         Premium             24           50

In [86]:
df['total_paid'] = df['monthly_fee'] * df['months_active']

In [89]:
df['loyalty'] = df['months_active'].apply(lambda x: 'Bronze' if x<6 else ('Silver' if x<12 else 'Gold'))

In [90]:
discounts = {
    'Premium': 0.9,
    'Student': 0.8,
    'Basic': 1.0
}
df['disscounted_fees'] = df['monthly_fee'] * df['membership_type'].map(discounts)

In [91]:
df[['first_name', 'last_name']] = df['name'].str.split(expand=True)
df = df.drop(columns=['name'])

In [92]:
df

,member_id,membership_type,months_active,monthly_fee,Total_Paid,total_paid,loyalty,disscounted_fees,first_name,last_name
0,101,Basic,3,30,90,90,Bronze,30.0,John,Doe
1,102,Premium,12,50,600,600,Gold,45.0,Alice,Smith
2,103,Basic,7,30,210,210,Silver,30.0,Bob,Johnson
3,104,Student,2,20,40,40,Bronze,16.0,Eva,Williams
4,105,Premium,24,50,1200,1200,Gold,45.0,Mike,Brown

In [93]:
import pandas as pd
import numpy as np

data = {
    'product_id': ['A-100', 'B-200', 'C-300', 'D-400', 'E-500'],
    'product_name': ['Smartphone X', '  Wireless Earbuds', 'Smart Watch ', 'Tablet Pro  ', 'Laptop Ultra'],
    'category': ['Phones', 'Audio', 'Wearables', 'Tablets', 'Computers'],
    'current_price': [799.99, ' 129.99 ', 199.50, '349.00', '999.00'],
    'units_in_stock': [45, 102, 28, '15', 7],
    'last_restock_date': ['2023-05-15', '2023-06-01', 'Invalid', '2023-06-10', 'NaN']
}

df = pd.DataFrame(data)
print("Original Messy Data:")
df

Original Messy Data:

,product_id,product_name,category,current_price,units_in_stock,last_restock_date
0,A-100,Smartphone X,Phones,799.99,45,2023-05-15
1,B-200,Wireless Earbuds,Audio,129.99,102,2023-06-01
2,C-300,Smart Watch,Wearables,199.5,28,Invalid
3,D-400,Tablet Pro,Tablets,349.00,15,2023-06-10
4,E-500,Laptop Ultra,Computers,999.00,7,NaN

In [99]:
df['product_id'] = df['product_id'].str.strip()
df['current_price'] = df['current_price'].str.strip().astype(float)
df['units_in_stock'] = df['units_in_stock'].astype(int)
df['last_restock_date'] = df['last_restock_date'].replace(['Invalid','NaN',''],np.nan)
df['last_restock_date'] = pd.to_datetime(df['last_restock_date'])

In [104]:
labels = ['Low','Medium','High']
bins = [0,20,50,np.inf]
df['stock_status'] = pd.cut(df['units_in_stock'],bins=bins,labels=labels)
lab = ['Budget','midrange','Premium']
bi = [0,200,800,np.inf]
df['price_tier'] = pd.cut(df['current_price'],bins=bi,labels=lab)
df['last_restock_date'] = df['last_restock_date'].replace(['Invalid','NaN',''],'Unknown')

In [106]:
df.loc[df['price_tier'] == 'Premium', 'current_price'] *= 1.15
df['estimated_value'] = df['current_price'] * df['units_in_stock']

In [107]:
df

,product_id,product_name,category,current_price,units_in_stock,last_restock_date,stock_status,price_tier,estimated_value
0,A-100,Smartphone X,Phones,NaN,45,2023-05-15,Medium,NaN,NaN
1,B-200,Wireless Earbuds,Audio,129.99,102,2023-06-01,High,Budget,13258.98
2,C-300,Smart Watch,Wearables,NaN,28,NaT,Medium,NaN,NaN
3,D-400,Tablet Pro,Tablets,349.00,15,2023-06-10,Low,midrange,5235.00
4,E-500,Laptop Ultra,Computers,1148.85,7,NaT,Low,Premium,8041.95

In [108]:
import pandas as pd
import numpy as np

data = {
    'order_id': ['#1001', '1002', '#1003', '1004', '1005', '1006'],
    'customer': ['john@email.com', 'ALICE@GMAIL.COM', 'bob_123@yahoo.com', np.nan, 'invalid', 'DAVID@shop.com'],
    'product': ['Laptop|16GB', 'Mouse (Wireless)', 'Keyboard', 'Monitor-24"', 'USB-C Cable', 'Phone_Case'],
    'category': ['Electronics', 'Electronics', 'Electronics', 'Electronics', 'Accessories', None],
    'price': ['$999.99', '$25.50', '45.00', 200.00, '10.99', ''],
    'date': ['2023-01-15', 'Invalid', '2023-01-20', '2023-01-18', 'NaN', '2023-01-22'],
    'rating': [5, 4, None, 3, 2, 5]
}
df = pd.DataFrame(data)
df

,order_id,customer,product,category,price,date,rating
0,#1001,john@email.com,Laptop|16GB,Electronics,$999.99,2023-01-15,5.0
1,1002,ALICE@GMAIL.COM,Mouse (Wireless),Electronics,$25.50,Invalid,4.0
2,#1003,bob_123@yahoo.com,Keyboard,Electronics,45.00,2023-01-20,NaN
3,1004,NaN,"Monitor-24""",Electronics,200.0,2023-01-18,3.0
4,1005,invalid,USB-C Cable,Accessories,10.99,NaN,2.0
5,1006,DAVID@shop.com,Phone_Case,None,,2023-01-22,5.0

In [129]:
#Data Cleaning 
#df['order_id'] = df['order_id'].str.replace('#','').astype(int)
df['domains'] = df['customer'].str.extract(r'@([\w.-]+)$')
df['product'] = df['product'].str.replace(r'[^a-zA-Z0-9]','',regex=True)
'''df['price'] = (df['price']
               .str.replace('$','',regex=False)
               .replace('','0')
               .fillna('0')
               .astype(float))'''
df['date'] = df['date'].replace(['Invalid','NaN',''],0).astype('datetime64[ns]')

In [151]:
#Feature Eng  
bins = [0,100,500,float('inf')]
labels = ['Budget', 'Mid', 'Premium']
df['price_tier'] = pd.cut(df['price'],bins=bins, labels=labels)
df['days_since_order'] = (pd.Timestamp('today') - df['date']).dt.days
df['email_provider'] = df['domains'].str.split('.').str[0]

In [155]:
df['price_tier'] = df.groupby('price_tier')['rating'].mean().round(2)

In [156]:
df['email_provider'].value_counts()

email_provider
email    1
GMAIL    1
yahoo    1
shop     1
Name: count, dtype: int64

In [159]:
pd.pivot_table(
    df,
    values='price',
    index='category',
    columns='price_tier',
    aggfunc='median',
    margins=True
)

Empty DataFrame
Columns: []
Index: []

In [160]:
df

,order_id,customer,product,category,price,date,rating,domains,price_tier,days_since_order,email_provider
0,1001,john@email.com,Laptop16GB,Electronics,999.99,2023-01-15,5.0,email.com,NaN,875,email
1,1002,ALICE@GMAIL.COM,MouseWireless,Electronics,25.50,1970-01-01,4.0,GMAIL.COM,NaN,20247,GMAIL
2,1003,bob_123@yahoo.com,Keyboard,Electronics,45.00,2023-01-20,NaN,yahoo.com,NaN,870,yahoo
3,1004,NaN,Monitor24,Electronics,0.00,2023-01-18,3.0,NaN,NaN,872,NaN
4,1005,invalid,USBCCable,Accessories,10.99,1970-01-01,2.0,NaN,NaN,20247,NaN
5,1006,DAVID@shop.com,PhoneCase,None,0.00,2023-01-22,5.0,shop.com,NaN,868,shop