In [1]:
import pandas as pd  
import numpy as np

In [15]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Score': [88, 92, 95, 70]
})
df

      Name  Age  Score
0    Alice   25     88
1      Bob   30     92
2  Charlie   35     95
3    David   40     70

In [19]:
df['Grade'] = df['Score'].map(lambda x: "A" if x>=90 else("B" if x>=80 else "C"))
df['Is_Senior'] = df['Age'].apply(lambda x: True if x>30 else False )
df[['Age','Score']].map(lambda x: x**2)
df

      Name  Age  Score Grade  Is_Senior
0    Alice   25     88     B      False
1      Bob   30     92     A      False
2  Charlie   35     95     A       True
3    David   40     70     C       True

In [20]:
import pandas as pd

data = {
    'Team': ['A', 'A', 'B', 'B', 'C', 'C'],
    'Player': ['P1', 'P2', 'P3', 'P4', 'P5', 'P6'],
    'Points': [10, 15, 20, 25, 30, 35],
    'Fouls': [1, 2, 0, 3, 2, 4]
}
df = pd.DataFrame(data)
df

  Team Player  Points  Fouls
0    A     P1      10      1
1    A     P2      15      2
2    B     P3      20      0
3    B     P4      25      3
4    C     P5      30      2
5    C     P6      35      4

In [39]:
team = df.groupby('Team')['Points'].sum().reset_index()
fouls = df.groupby('Team')['Fouls'].mean().reset_index()
points = df.groupby('Team')['Points'].max().reset_index()
number = df.groupby('Team').size().reset_index(name='Player_Count')
agg = df.groupby('Team').agg({'Points': 'mean', 'Fouls': 'sum'}).reset_index()
agg

  Team  Points  Fouls
0    A    12.5      3
1    B    22.5      3
2    C    32.5      6

In [69]:
import pandas as pd

data = {
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Product': ['A', 'A', 'B', 'C', 'B', 'B', 'A', 'A', 'C', 'C'],
    'Sales': [120, 150, 200, 130, 180, 160, 140, 170, 190, 110],
    'Discount': [5, 10, 7, 6, 5, 8, 9, 4, 6, 7],
    'Returns': [1, 0, 2, 1, 1, 3, 0, 1, 2, 2],
    'Cost': [80, 100, 120, 90, 110, 105, 85, 95, 115, 70]
}
df = pd.DataFrame(data)
df

  Region Product  Sales  Discount  Returns  Cost
0  North       A    120         5        1    80
1  South       A    150        10        0   100
2   East       B    200         7        2   120
3   West       C    130         6        1    90
4  North       B    180         5        1   110
5  South       B    160         8        3   105
6   East       A    140         9        0    85
7   West       A    170         4        1    95
8  North       C    190         6        2   115
9  South       C    110         7        2    70

In [95]:
df['Profit'] = df['Sales'] - df['Cost']
profit_region = df.groupby('Region')['Profit'].sum().reset_index()
df['Return_rate'] = df['Returns'] / df['Sales']
avg_discount = df.groupby('Product').agg({'Discount':'mean','Return_rate':'mean'}).reset_index()
avg_profit = df.groupby(['Region','Product'])['Profit'].mean().reset_index()
avg_profit.sort_values(by='Region',ascending=True)
region_product = df.groupby(['Region','Product']).agg({'Sales':'sum','Cost':'mean'}).reset_index()
high = df.groupby(['Product','Region'])['Sales'].sum().reset_index()
high.max()

Product       C
Region     West
Sales       200
dtype: object

In [96]:
data = {
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Product': ['A', 'A', 'B', 'C', 'B', 'B', 'A', 'A', 'C', 'C'],
    'Sales': [120, 150, 200, 130, 180, 160, 140, 170, 190, 110],
    'Discount': [5, 10, 7, 6, 5, 8, 9, 4, 6, 7],
    'Returns': [1, 0, 2, 1, 1, 3, 0, 1, 2, 2],
    'Cost': [80, 100, 120, 90, 110, 105, 85, 95, 115, 70]
}
df = pd.DataFrame(data)
df

  Region Product  Sales  Discount  Returns  Cost
0  North       A    120         5        1    80
1  South       A    150        10        0   100
2   East       B    200         7        2   120
3   West       C    130         6        1    90
4  North       B    180         5        1   110
5  South       B    160         8        3   105
6   East       A    140         9        0    85
7   West       A    170         4        1    95
8  North       C    190         6        2   115
9  South       C    110         7        2    70

In [107]:
sales = pd.pivot_table(df,values='Sales',index='Region',columns='Product',aggfunc='sum')
discout = pd.pivot_table(df,values='Discount',index='Region',columns='Product',aggfunc='mean')
sold = pd.pivot_table(df,values='Sales',index='Region',columns='Product',aggfunc='count')
pd.crosstab(df['Region'], df['Product'])
pd.crosstab(df['Region'], df['Product'], values=df['Sales'], aggfunc='sum')

Product      A      B      C
Region
East     140.0  200.0    NaN
North    120.0  180.0  190.0
South    150.0  160.0  110.0
West     170.0    NaN  130.0

In [108]:
data = {
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Product': ['A', 'A', 'B', 'C', 'B', 'B', 'A', 'A', 'C', 'C'],
    'Sales': [120, 150, 200, 130, 180, 160, 140, 170, 190, 110],
    'Discount': [5, 10, 7, 6, 5, 8, 9, 4, 6, 7],
    'Returns': [1, 0, 2, 1, 1, 3, 0, 1, 2, 2],
    'Cost': [80, 100, 120, 90, 110, 105, 85, 95, 115, 70]
}
df = pd.DataFrame(data)
df

  Region Product  Sales  Discount  Returns  Cost
0  North       A    120         5        1    80
1  South       A    150        10        0   100
2   East       B    200         7        2   120
3   West       C    130         6        1    90
4  North       B    180         5        1   110
5  South       B    160         8        3   105
6   East       A    140         9        0    85
7   West       A    170         4        1    95
8  North       C    190         6        2   115
9  South       C    110         7        2    70

In [120]:
df.sort_values(by='Sales',ascending=False)
df.sort_values(by=['Region','Sales'],ascending=[True,False])
df['Profit'] = df['Sales'] - df['Cost']
df['Profit'].rank(ascending=False).reset_index()
df.reset_index()
df.sort_index()

  Region Product  Sales  Discount  Returns  Cost  Profit
0  North       A    120         5        1    80      40
1  South       A    150        10        0   100      50
2   East       B    200         7        2   120      80
3   West       C    130         6        1    90      40
4  North       B    180         5        1   110      70
5  South       B    160         8        3   105      55
6   East       A    140         9        0    85      55
7   West       A    170         4        1    95      75
8  North       C    190         6        2   115      75
9  South       C    110         7        2    70      40